### ISSUE TITLE
Immediate crash using Intel's Arc card - A380

### ISSUE THREAD

**Issue by NikosDi** [tigros/Whisperer#21] opened 2023-09-17 15:55 UTC
Hello.

I was looking for a batch processing mode of Whisper https://github.com/Const-me/Whisper and I think this is the app here. proposed by the developer.

Unfortunately, it crashes immediately with the attached pop-up message using my Intel Arc A380 6GB VRAM card (latest drivers - Latest Win 11 Pro all updates):
<img width="231" alt="Intel Arc crash" src="https://github.com/tigros/Whisperer/assets/31016247/9805336b-8363-4ca1-8a8a-ee2e846e4b81">

1) Is it possible to fix it ?

2) I'm looking forward to batch processing of one by one file, not as many as possible at the same time.

Does this app support this mode ?
Is it possible to add it ?

Thank you.

**Comment by tigros** [comment] 2023-09-17 18:26
Hi,

Can you run these commands from cmd and paste results?

    reg query hklm\SYSTEM\CurrentControlSet\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318} /f 00* /k
    reg query hklm\SYSTEM\ControlSet001\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\0000 /v HardwareInformation*
    reg query hklm\SYSTEM\ControlSet001\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\0001 /v HardwareInformation*

Also please run attached program in cmd and paste that too.
[printgpu.zip](https://github.com/tigros/Whisperer/files/12643441/printgpu.zip)

Thanks

**Comment by NikosDi** [comment] 2023-09-17 19:22
I hope it's clear.

<img width="948" alt="Intel" src="https://github.com/tigros/Whisperer/assets/31016247/126aa227-10f6-4828-9452-8acd8a0ceca1">

**Comment by NikosDi** [comment] 2023-09-17 19:36
And this is the results of the same commands and program for Skylake iGPU - HD 530

Whisperer crashed with the same output.

![Intel2](https://github.com/tigros/Whisperer/assets/31016247/fcf19daa-4d92-402e-8f19-1b35bd133d83)

**Comment by tigros** [comment] 2023-09-17 21:07
Hi,

I would complain to Intel for not having HardwareInformation.qwMemorySize, they should've put that!

I'm looking for alternative but it's not easy to find so far. Will keep looking.

**Comment by tigros** [comment] 2023-09-18 00:30
ok please try attached whisperer.exe.

also in cmd please paste result of included GPUmembyproc.exe

[Whisperer.zip](https://github.com/tigros/Whisperer/files/12644047/Whisperer.zip)

**Comment by NikosDi** [comment] 2023-09-18 03:32
I will post to Intel's forum regarding the Memory size.

Using HD 530 I got an Unhandled exception of .NET Framework but after pressing "Continue" the program seems to work.

GPUmembyproc.exe returns 0

The whole exception is here:
![image](https://github.com/tigros/Whisperer/assets/31016247/bb3b88e2-2ec2-466e-bf04-1569a8e987f3)

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at whisperer.Form1.toproper(String s)
   at whisperer.Form1.Form1_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
whisperer
    Assembly Version: 2.8.0.0
    Win32 Version: 2.8.0.0
    CodeBase: file:///C:/various_progs/Whisper/Whisperer/whisperer.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9172.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
ObjectListView
    Assembly Version: 2.9.1.1072
    Win32 Version: 2.9.1.0
    CodeBase: file:///C:/various_progs/Whisper/Whisperer/ObjectListView.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by tigros** [comment] 2023-09-18 03:43
i guess the error is because the saved lang in the registry was blank, because of earlier crash..

you need to try this on arc PC, intel HD not expected to work.

**Comment by NikosDi** [comment] 2023-09-18 03:46
OK, I'll try it and post again here with A380

What is the saved lang in the registry ?

**Comment by tigros** [comment] 2023-09-18 03:49
data saved in the registry here:

    reg query hkcu\SOFTWARE\tigros\whisperer

includes language.

**Comment by NikosDi** [comment] 2023-09-18 04:05
Right.
I deleted the registry folder "tigros" and re-run the program with no .NET complaints

Using HD 530 and model "ggml-medium.en.bin" it crashes with memory complaints, although I have selected 1 files max

I can use HD 530 with WhisperDesktop v1.12 and ggml-medium.en.bin with no problem as iGPU leverages up to 4GB of my RAM

![Screenshot 2023-09-18 065528](https://github.com/tigros/Whisperer/assets/31016247/b57c2cf1-b10f-42b6-b59c-a7cd0e74d218)

**Comment by tigros** [comment] 2023-09-18 04:12
I was able to fix things on my mom's new AMD laptop because I had access to it via teamviewer, no access to intel HD to troubleshoot.

Please try Arc PC, that's the big question.

**Comment by NikosDi** [comment] 2023-09-18 04:21
Everything look fine with Arc.
Here is the output of GPUmem.
<img width="566" alt="image" src="https://github.com/tigros/Whisperer/assets/31016247/1e9b8449-910d-4348-8b2a-7ff072fa9844">

A few issues regarding the first few minutes with the app:

1) It doesn't have a progress bar or anything else to report what is going on with the process during runtime.

I can only see the number of "Completed" files changing.

2) It doesn't keep user's preferences like:

a) "same as input folder"
b) Number of files "max at once"

Haven't tried the other options yet.
I guess the other thing I asked regarding processing one file only can be done my selecting "max at once"

**Comment by tigros** [comment] 2023-09-18 04:26
yes you can set max at once to 1.

some have asked about progress bar before, nope can't do it, the way to know it's working is the Go button says Cancel instead.

I guess I will put a v2.9 soon, hopefully keeps working with other setups.

**Comment by NikosDi** [comment] 2023-09-18 04:38
OK.

And what about keeping user prefs ?

Also, since you are using WhisperDesktop for GPU transcribing, what preferences this app Whisperer use for GPU advanced options ?

I mean "Compute shaders" and "Reshaped matrix multiply" as WhisperDesktop says in the app.

**Comment by tigros** [comment] 2023-09-18 04:42
ok i'll add the 2 prefs since it's easy to do.

it uses main.exe not whisperdesktop, if you type main.exe in cmd you'll see what's available.

**Comment by NikosDi** [comment] 2023-09-18 04:55
It would be useful to add as many use prefs as you can, like:
"srt", "txt", "vtt". "when done", "skip if output exists", "translate to english" etc

You get the idea.

Also, if progress bar is not possible, maybe a total time processing after batch job is done.
A total completion time.

Another helpful addition would be to provide a Windows explorer windows when the user click on the path selection of the "Model path" and "Output dir"

It's unusual trouble to copy paste the path from Windows explorer to the app.

**Comment by tigros** [comment] 2023-09-18 05:03
ya maybe a clock showing elapsed time i guess so some kind of movement

**Comment by NikosDi** [comment] 2023-09-18 05:24
What is main.exe ?

Does it support word level timestamps ?

It seems that is uses the same model ggml-medium.en.bin differently than WhisperDesktop.

It produces different results using the same input file.

Also, it doesn't expose those options I mentioned before.

Does it work with ggml-large-v1.bin and ggml-large.bin (v2) models ?

**Comment by tigros** [comment] 2023-09-18 06:23
main.exe is command line interface or cli.

v1, v2 should work.

to add more options you'd have to ask in Const-me repo.

**Comment by NikosDi** [comment] 2023-09-18 06:53
Yes, I found everything and doing some tests and benchmarks.

It seems that the cli version of WindowsDesktop the cli.zip has a different version of whisper.dll inside the cli.zip than the one you are using for Whisperer.
The latest Whisper.dll file is inside the cli.zip, the library.zip and the WindowsDesktop.zip

Have you seen that ?

Also, I compared apples with oranges when I said in the previous post that for the same input, Whisperer and WhisperDesktop are producing different results.
Yes, they are because I used different model (medium.en vs large-v1). 
Using the same model they both produce the same result for the same input.

Last one for now, when I posted before regarding the path and an easier way to select it, I mean something like the "Pick files" button you have already implemented.

**Comment by tigros** [comment] 2023-09-18 07:43
thanks for letting me know about newer version.

Please try this, tell me if anything missing before i commit.

Thanks.

[Whisperer.zip](https://github.com/tigros/Whisperer/files/12645538/Whisperer.zip)

**Comment by NikosDi** [comment] 2023-09-18 08:02
You fixed everything in no time, awesome!

A few more things to add before commit:

1) When I pick the files and they are included in the app, they should also automatically selected. No manual  selection should be necessary.

2) When I change something at the lower section of the app, like model path, the files from the upper level of the app should remain selected automatically. It looses the selection even right now with the manual selection. All the files should always be auto selected automatically.

3) When I use the "max at once" as 1 by 1 file processing, when the first one completes I see the button from "cancel" changing to "Go" although the batch processing hasn't completed yet. I think it's a bug.

**Comment by tigros** [comment] 2023-09-18 08:32
3, 4 you have to multi-select, use ctrl-a to select all, or hold shift+click to select range, or ctrl+click to multi-select individually, there's a count next to the max at once.

**Comment by NikosDi** [comment] 2023-09-18 08:42
I have updated my list above with different numbering and content!

I think you replied to the previous one.

**Comment by tigros** [comment] 2023-09-18 09:23
3 and 4 what is count next to max at once? if it's 1 / ... then you aren't multi-selecting.

here's one to try.

[Whisperer.zip](https://github.com/tigros/Whisperer/files/12646275/Whisperer.zip)

**Comment by tigros** [comment] 2023-09-18 09:32
maybe the srt's exist so getting skipped? in that case just uncheck the "skip if exists"

**Comment by NikosDi** [comment] 2023-09-18 09:36
No the folder is clear.

Last time I did the test, I was using just two files.

Try just two files and see if you can replicate the issue.

**Comment by tigros** [comment] 2023-09-18 09:50
it would be quite odd looking at the code, no i can't reproduce.

there was a bug in last one, use this one.

[Whisperer.zip](https://github.com/tigros/Whisperer/files/12646463/Whisperer.zip)

**Comment by NikosDi** [comment] 2023-09-18 12:32
The first two additions are working like a charm.

Regarding 3, 4 issues I managed to reproduce the bug which has slightly changed its behavior:

1) If you have selected the default option "Skip if output exists"  everything works fine

2) If you uncheck "skip if output exists" try to create or let the program create a new clean folder and select it as output folder.

3) With the above option unchecked, add two files and set the "max at once" to 1

4) After the completion of the processing, close the app and open the folder of the output deleting all .srt files

5) Open again the app without clearing the files added and without changing anything run the task again.

6) At the end you will see the "Completed" figure saying 1 instead of 2 (the app transcribes successfully both files) and if you go to the output folder you will find both .srt files and one wav which shouldn't be here.

Probably this is the reason which says "Completed" 1 instead of 2.

Elapsed time works now in all cases and the button never changes to "Go" during processing .

I had to delete the whole "tigros" folder in registry and start from the beginning to have this output which is close to perfect.

**Comment by tigros** [comment] 2023-09-18 13:26
it's weird you had a left over wav file, not sure what happened there, still can't reproduce.

i need to test this on my mother's laptop, probably broken for integrated GPU, that will be later tonight.

**Comment by NikosDi** [comment] 2023-09-18 15:30
You have to leave both "Skip if output exists" and "Same as input folder" unchecked.
And create a new, clean output folder.

If you can't reproduce the weird behavior, never mind.

I think it's better to release the new version, it will have a lot of changes worth checking for all, along with Intel's Arc support.

Thanks for the additions and the batch processing app.

**Comment by tigros** [comment] 2023-09-19 00:51
it's possible you closed/reopened the app without realizing there was a main.exe still running, when you cancel or close it doesn't kill main.exe, you could use task manager and look for main.exe. So beware of that.

I've tested on mom'c PC, all good, I may have fixed for intel HD too. Please run included GPUmembyproc.exe on your Intel PC and paste results.

Thanks.
[Whisperer.zip](https://github.com/tigros/Whisperer/files/12654505/Whisperer.zip)

**Comment by NikosDi** [comment] 2023-09-19 04:05
Hi.

The main wasn't running because I've been waiting for the app to produce two .srt files.
So, when everything completed there were two .srt files and one .wav.

Anyway, next time I'll try to record a video and upload it.

The last version runs flawlessly with my Intel iGPU HD 530, reporting the proper GPU VRAM of 4GB.

All clear to unleash the beast.

**Comment by tigros** [comment] 2023-09-19 05:46
ok v2.9 released https://github.com/tigros/Whisperer/releases/tag/2.9

Thanks for all your work!

**Closed by tigros** 2023-09-19 05:46 UTC
